[project]
name = "todos-cli"
version = "0.1.0"
description = "Simple Command-line tool to track and manage todos."
authors = [{ name = "Shubham V" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.12"

